name: DevAthlon
version: 0.0.1
main: de.nonamelabs.devathlon.Plugin_DevAthlon
commands: 
  startgame:
    description: startet das spiel
    usage: /startgame <players> <ghosts>
  addplayerspawn:
    description: Fuegt einen weiteren Spieler Spawn hinzu
    usage: /addplayerspawn
  resetplayerspawns:
    description: Setzt die Spieler Spawns zurueck
    usage: /resetplayerspawns
  setghostspawn:
    description: Setzt den Geister Spawn
    usage: /setghostspawn
  stopgame:
    description: Stoppt das Spiel
    usage: /stopgame
  setMapCorner1:
    description: Setzt die erste Ecke des Spiels
    usage: /setMapCorner1
  setMapCorner2:
    description: Setzt die zweite Ecke des Spiels
    usage: /setMapCorner2